### ISSUE TITLE
Unrelated Subject

### ISSUE THREAD

**Issue by GATICAM** [PejmanPoh/jupyter-test#1]
Hi @PejmanPoh!

I am not quite a coder, engineer, programmer, or related. I've been just looking for an alternative to creating a bot for the berlin service portal since is impossible to get an appointment and I am soon to lose my opportunity for residency. I noticed in the issues section of that repository, that you were trying the same bot code and were having the same problem when trying this option. Today I got again into the web and check that you had a new solution... I would be absolutely grateful if you can help me with this matter.

As I said, I'm not familiar with this area of expertise, I'm just trying new ways to make this happen instead of committing every single minute to refresh the page with no luck for 3 months now.

If you have any chance of helping me out with this it would be a savior. Let me know if you like to get in contact ip.

btw I apologize for invading one of your repositories issue just to get in touch with you.

**Comment by PejmanPoh** [comment]
Hey Gaticam, give me a way to contact you privately. I'll see what I can do.

**Comment by GATICAM** [comment]
my email is mariajose.gatica1989@gmail.com
